// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/pizza.proto

package pizza

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The Request: What the 'Blitz' has to send to place an order correctly
type SubmitOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	PizzaId       int32                  `protobuf:"varint,2,opt,name=pizza_id,json=pizzaId,proto3" json:"pizza_id,omitempty"`
	CustomerId    int32                  `protobuf:"varint,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOrderRequest) Reset() {
	*x = SubmitOrderRequest{}
	mi := &file_proto_pizza_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrderRequest) ProtoMessage() {}

func (x *SubmitOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pizza_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrderRequest.ProtoReflect.Descriptor instead.
func (*SubmitOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_pizza_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitOrderRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *SubmitOrderRequest) GetPizzaId() int32 {
	if x != nil {
		return x.PizzaId
	}
	return 0
}

func (x *SubmitOrderRequest) GetCustomerId() int32 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

// The Response: What the 'Kitchen' sends back
type SubmitOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOrderResponse) Reset() {
	*x = SubmitOrderResponse{}
	mi := &file_proto_pizza_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrderResponse) ProtoMessage() {}

func (x *SubmitOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pizza_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrderResponse.ProtoReflect.Descriptor instead.
func (*SubmitOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_pizza_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *SubmitOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitOrderResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_proto_pizza_proto protoreflect.FileDescriptor

const file_proto_pizza_proto_rawDesc = "" +
	"\n" +
	"\x11proto/pizza.proto\x12\x05pizza\"k\n" +
	"\x12SubmitOrderRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x19\n" +
	"\bpizza_id\x18\x02 \x01(\x05R\apizzaId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\x05R\n" +
	"customerId\"Z\n" +
	"\x13SubmitOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg2V\n" +
	"\x0eKitchenService\x12D\n" +
	"\vSubmitOrder\x12\x19.pizza.SubmitOrderRequest\x1a\x1a.pizza.SubmitOrderResponseB.Z,github.com/juancrfig/pizzageddon/proto/pizzab\x06proto3"

var (
	file_proto_pizza_proto_rawDescOnce sync.Once
	file_proto_pizza_proto_rawDescData []byte
)

func file_proto_pizza_proto_rawDescGZIP() []byte {
	file_proto_pizza_proto_rawDescOnce.Do(func() {
		file_proto_pizza_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pizza_proto_rawDesc), len(file_proto_pizza_proto_rawDesc)))
	})
	return file_proto_pizza_proto_rawDescData
}

var file_proto_pizza_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_pizza_proto_goTypes = []any{
	(*SubmitOrderRequest)(nil),  // 0: pizza.SubmitOrderRequest
	(*SubmitOrderResponse)(nil), // 1: pizza.SubmitOrderResponse
}
var file_proto_pizza_proto_depIdxs = []int32{
	0, // 0: pizza.KitchenService.SubmitOrder:input_type -> pizza.SubmitOrderRequest
	1, // 1: pizza.KitchenService.SubmitOrder:output_type -> pizza.SubmitOrderResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_pizza_proto_init() }
func file_proto_pizza_proto_init() {
	if File_proto_pizza_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pizza_proto_rawDesc), len(file_proto_pizza_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pizza_proto_goTypes,
		DependencyIndexes: file_proto_pizza_proto_depIdxs,
		MessageInfos:      file_proto_pizza_proto_msgTypes,
	}.Build()
	File_proto_pizza_proto = out.File
	file_proto_pizza_proto_goTypes = nil
	file_proto_pizza_proto_depIdxs = nil
}
